US-2.12 - Added switcher from MUI to edit company form, added active …
itechart-warehouse/frontend pull request #12
Opened 2022-02-18 18:42 UTC by StoreCarCharIsInNoSave

…field to clientApi

2022-02-20 18:49 UTC, Lonely-fr approved these changes

2022-02-21 05:35 UTC, Laranto-spb requested changes
All work fine (2 unused things to remove)

2022-02-21 05:35 UTC, Laranto-spb commented on src/components/forms/company-form/EditCompanyForm.tsx
> +
Unused variable, 48 row - console log

2022-02-21 11:15 UTC, alllpim approved these changes

2022-02-21 11:16 UTC, Laranto-spb approved these changes

2022-02-21 11:20 UTC, merged