W-41 Added page, lists, buttons for CRUD
itechart-warehouse/frontend pull request #78
Opened 2022-06-23 09:37 UTC by alllpim

https://trello.com/c/9ViUij0l

URL: http://localhost:3006/catalog

2022-06-24 10:21 UTC, MonkeyKingBar-bit requested changes
U need to check the urls & fix adding data
![image](https://user-images.githubusercontent.com/60444425/175517494-cd40d335-0fd3-4ddd-8a7e-eeeb95450c97.png)

2022-06-24 10:21 UTC, MonkeyKingBar-bit commented on src/components/dialogs/CountryCatalogDialog.tsx
> +              </Button>
Dialog doesn't close, when click on submit btn
And it doesn't add country in country table, only in console
![image](https://user-images.githubusercontent.com/60444425/175514745-c806c9a5-543d-4764-bbeb-87fcf41c1839.png)

2022-06-24 10:21 UTC, MonkeyKingBar-bit commented on src/pages/catalogs/countries-cities/CountriesCitiesPage.tsx
> +import { clearError } from "../../../store/errorSlice";
Maybe need to delete unused files

2022-06-28 12:20 UTC, NDragneelL9 approved these changes

2022-06-28 19:38 UTC, alllpim commented on src/components/dialogs/CountryCatalogDialog.tsx
> +              </Button>
try to use last versions of back and front servers for testing

2022-07-01 10:40 UTC, Lonely-fr approved these changes

2022-07-01 11:32 UTC, helmy-er approved these changes

2022-07-04 13:41 UTC, MonkeyKingBar-bit approved these changes

2024-12-09 03:43 UTC, closed without merging